[tool.poetry]
name = "phylogenetic-indices"
version = "1.0.0"
description = ""
authors = ["Domingos Dias"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
