name: CI/CD
on: [push, pull_request]

jobs:
  test:
    runs-one: ubuntu-latest

    steps:
      - name: Clone project
        uses: actions/checkout@v3.3.0

      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'